### ISSUE TITLE
設定ファイルの場所に関して (/yaml/SC_Config.yaml)

### ISSUE THREAD

**Issue by 610t** [NoRi-230401/BinsPack-for-StackChan-Core2#1]
設定ファイルなのですが、
- 01_btSpeaker.bin

などで使われている
/yaml/SC_Config.yaml
も有効になっているようです。
Bluetoothスピーカー名(bluetooth:->device_name: "Core2")や起動時ボリューム(bluetooth:->start_volume: 100)が変えたりできるので、これも有効なことがREADME.mdのどこかに記述があれば良いかなと思います。

**Comment by NoRi-230401** [comment]
今度、READMEに追加します。

**Comment by NoRi-230401** [comment]
READMEに追加しました。2024-06-23
情報ありがとうございました。
